### ISSUE TITLE
Spacebar only goes up, gravity isn’t pulling me back down

### ISSUE THREAD

**Issue by avidrissman** [s4y/nye2021#3]
On my Ergodox EZ (that particular keyboard might matter), when I press the space bar I go up in the Z direction, but when I release the spacebar I don’t fall back down.

Not seeing that on https://homewardbound.theweeklyweekly.com/ so maybe it’s due to a change since then?

**Comment by avidrissman** [comment]
Plugged in my Kinesis Advantage, reloaded, and falling works now. Is Chrome doing something weird with the spacebar with the Ergodox? Lemme know what to look for.

**Comment by avidrissman** [comment]
<img width="803" alt="Screen Shot 2020-12-31 at 11 45 49 PM" src="https://user-images.githubusercontent.com/3914435/103433621-61b62e00-4bc2-11eb-87be-355732ab1c1b.png">

This might be affecting a few other people too.

**Comment by s4y** [comment]
Does tapping the shift key make this go away?

**Comment by avidrissman** [comment]
I can’t make it repro any more.

**Comment by s4y** [comment]
OK, definitely let me know if it comes back.
